name: Sync

on:
  schedule:
  - cron: '0 0 */1 * *' # every day
  workflow_dispatch:

env:
  SYNC_REPO: benbusby/whoogle-search

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout sync-repo
        uses: actions/checkout@v3
        with:
          repository: ${{ env.SYNC_REPO }}
          path: './sync'
      - name: copy from sync-repo
        run: |
          rm -rf ./sync/misc/heroku-regen.sh
          cp -r  ./sync/app .
          cp -r  ./sync/misc .
          cp -r  ./sync/requirements.txt .
          cp -r  ./sync/run .
          cat ./sync/Dockerfile | sed -e "s/\#COPY/COPY/g" > ./Dockerfile
          mv ./sync/docker-compose.yml ./docker-compose.yml.backup
          mv ./sync/whoogle.template.env .
          rm -rf ./sync
      - name: Get last commit message
        id: last-commit-message
        run: |
          echo "::set-output name=msg::$(git log -1 --pretty=%s)"
      - uses: EndBug/add-and-commit@v9
        with:
          message: ${{ steps.last-commit-message.outputs.msg }}
          committer_name: GitHub Actions
          committer_email: actions@github.com
